### ISSUE TITLE
Tutorial Data for "SEACell_domain_adapt.ipynb" not available

### ISSUE THREAD

**Issue by schae211** [dpeerlab/SEACells#10]
$ wget https://dp-lab-data-public.s3.amazonaws.com/SEACells/cd34_multiome_rna_with_labels.h5ad -O cd34_multiome_rna_with_labels.h5ad
--2022-04-12 16:44:06--  https://dp-lab-data-public.s3.amazonaws.com/SEACells/cd34_multiome_rna_with_labels.h5ad
Resolving dp-lab-data-public.s3.amazonaws.com (dp-lab-data-public.s3.amazonaws.com)... 52.217.101.236
Connecting to dp-lab-data-public.s3.amazonaws.com (dp-lab-data-public.s3.amazonaws.com)|52.217.101.236|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-12 16:44:07 ERROR 404: Not Found.

The files for the other tutorials are available.

**Comment by ManuSetty** [comment]
Thank you for spotting the error. There was a permissions issue which has been fixed now.
