### ISSUE TITLE
SEACells on integrated dataset

### ISSUE THREAD

**Issue by mainciburu** [dpeerlab/SEACells#13]
Hi, 
I'd like to apply SEACells to a dataset with multiple samples from the same condition. It's very heterogeneous, as they are samples from patients with cancer, but still the same condition. I'm wondering which is the best way to use SEACells, and I'm debating between two options:

1- Replicate the COVID dataset workflow in your preprint: run SEACells independently per sample => merge metacell matrices => integrate with Harmony => run SEACells on Harmony reduction. 

2- Alternative pipeline: Integrate every sample with Harmony at the cell level => run SEACells on Harmony reduction. 

I'm personally inclined to use the second option, as I see more compact metacells across the UMAP plot and more metacells with cells from just 1-2 clusters. But I'd like to ask whether you think it is appropriate to do this. 

Thanks a lot!

**Comment by ManuSetty** [comment]
Given the heterogeneity, option (2) does sound a marginally better choice!

**Comment by mainciburu** [comment]
Thank you! I'll do that then
