### ISSUE TITLE
Which modality to use in Multiome for metacell inference

### ISSUE THREAD

**Issue by PauBadiaM** [dpeerlab/SEACells#14]
Hi,

In Multiome data which data modality would you recommend to use for the inference of metacells? RNA or ATAC?
I'm asking because in this [tutorial](https://github.com/dpeerlab/SEACells/blob/main/notebooks/SEACell_ATAC_analysis.ipynb) you use ATAC but according to your biorxiv you mention that is actually harder:

> As a further challenge, we ran Palantir on aggregated RNA from metacells computed on the ATAC modality, since the sparsity of scATAC-seq data renders cell-state identification much more difficult

I know it depends on the biological context but, would you recommend as a rule of thumb to use RNA instead for metacell inference? What do you think?

Thank you for your time!

**Comment by ManuSetty** [comment]
Thank you for your query. For peak-gene associations, gene score computation etc, we do recommend the use of ATAC modality for metacell identification.

**Comment by PauBadiaM** [comment]
Thanks for the response! 
Alright so for state definition better use RNA, but for epigenome analysis better use ATAC, makes sense.
In any case, are you thinking on making a joint metacell inference step? Something like an averaged aggregation coming from RNA and ATAC at the same time?
Thank you for your time

**Comment by ManuSetty** [comment]
Joint metacell inference is an interesting idea and we are exploring a few options. We think a kernel representation that captures both modalities might be the best option here. For eg: MOFA+ generates a low embedding using multiple modalities. One can construct the nearest neighbor graph using the jointly learned embedding and generate a kernel which can then serve as input to SEACells.

**Comment by PauBadiaM** [comment]
Thanks for the feedback @ManuSetty! This makes a lot of sense, I'll play around this idea.

**Comment by ulyssebaruchel** [comment]
@PauBadiaM I would be curious to know (or even better, see) what is the best way to proceed you found by playing around with this idea, please. 
@ManuSetty I would also love to know if your team has a reach a conclusion on this, please.
Thank you for your time
