### ISSUE TITLE
Different metacells gained when repeating analysis on same data set

### ISSUE THREAD

**Issue by marie3003** [dpeerlab/SEACells#16]
Hi,
thanks again for your package:).

I've noticed  that whenever I run the metacell calculation on the same dataset, I get different initialized archetypes and because of that different metacells. I tried to add a random seed via numpy in the notebook but I'm still getting varying results.

Do you provide a solution for that I've overseen? 
Thanks a lot and best regards,
Marie

**Comment by ManuSetty** [comment]
Hello there - we are trying to figure this out. In the meantime, you could save the initial set of points and use as input to the second run which should reproduce the results.
