### ISSUE TITLE
number of SEACells

### ISSUE THREAD

**Issue by roshan9128** [dpeerlab/SEACells#2]
Hi, 

I ran SEACells requesting for 700 SEACells but I am getting only 543 SEACell. Any suggestions why this is happening? It also takes a long time on my data with default parameters (I have about 60K cells) so I did not try if simply re-running would change the number of SEACells I obtain, yet.

**Comment by ManuSetty** [comment]
This should be fixed in 57332279690d76c54f18ce8fb2dae01e802cbb98
