### ISSUE TITLE
Multiome Dataset

### ISSUE THREAD

**Issue by Sayyam-Shah** [dpeerlab/SEACells#22]
Hello,

I hope you are doing well. Thank you for the amazing tool.

I have a multiome dataset on the same cells and would like to take advantage of SEAcells. Would you recommend I run the seacell algorithm on both modalities separately and map the ATAC seacells to the RNA seacells?

**Comment by ManuSetty** [comment]
We recommend using the ATAC metacells for the use of gene-peak associations, gene scores and other ATAC related computation.

**Comment by Sayyam-Shah** [comment]
Interesting, thank you! Sorry to fully understand the workflow, the following steps would be to compute the ATAC metacells using SEACells.core.SEACells while inputting the X_svd and number of metacells (ex. 10k). From there, I can compute gene scores using SEACells.genescores.prepare_multiome_anndata which should spit out the RNA metacells. 

I am using seacells to run scenic plus on the multiome data. Scenic plus first runs cistopic on the ATAC data and identifies transcription factors using the RNA on the same cells.

**Comment by ManuSetty** [comment]
You can also try using the SCENIC+ latent representation to compute metacells instead of SVD.

**Comment by Sayyam-Shah** [comment]
That's an amazing idea. I assume you are referring to the reduction method used to generate the UMAP with pycistopic. 

From there, I can compute the ATAC and RNA seacells using the latent representation from cistopic on the full dataset. Then I can run cistopic again on the seacells and run scenic+ with the RNA seacells.
