### ISSUE TITLE
SeaCells analysis for each cell type

### ISSUE THREAD

**Issue by fl-yu** [dpeerlab/SEACells#25]
Given that the cell number is high, runtime and memory required increased exponentially, I wonder if I can perform SeaCell analysis for each cell type or split the datasets into parts and process them individually? Thank you!

**Comment by sitarapersad** [comment]
Hi! Yes you can definitely do this - we recommend this e.g. for processing different samples. However, the major caveat is if you have a highly continuous dataset, e.g. some type of trajectory, then you may be losing some information about continuous processes at the boundaries each each cell type.
