### ISSUE TITLE
Cannot initialize_archetypes

### ISSUE THREAD

**Issue by GuiSeSanz** [dpeerlab/SEACells#30]
Hello! 
I'm trying to run the example, but I'm facing the following error...
I've installed the package by cloning the repository and running the setup.py without errors.
After downloafing the example data I encounter: 

```
>>> model.initialize_archetypes()
Building kernel on X_pca
Computing diffusion components from X_pca for waypoint initialization ... 
Determing nearest neighbor graph...
Done.
Sampling waypoints ...
Done.
Selecting 81 cells from waypoint initialization.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/SEACells/SEACells/core.py", line 127, in initialize_archetypes
    greedy_ix = self._get_greedy_centers(n_mcs=from_greedy + 10)
  File "/root/SEACells/SEACells/core.py", line 243, in _get_greedy_centers
    n = K.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape' 
```

What can be happening here?

Python version: Python 3.8.16

**Comment by sitarapersad** [comment]
Hi! Quick question to help me debug - did you run model.construct_kernel_matrix() before trying to initialize archetypes?

**Comment by GuiSeSanz** [comment]
Sorry, that was my bad, I totally scramble the order and run the initialize_archetypes prior to construct_kernel_matrix.

Actually I'm now able to run properly the pipeline 👍

**Comment by Sally-Xiaowei** [comment]
I am wondering how to set n_SEACells and n_waypoint_eigs. The n_SEACells was set using the cell number/75 and  n_waypoint_eigs was set to 10. But, there is a hug " index 9 is out of bounds for axis 0 with size 7" when using the "model.initialize_archetypes()" function.
