### ISSUE TITLE
Reproducible example for the PBMC dataset

### ISSUE THREAD

**Issue by lebf3** [dpeerlab/SEACells#32]
Hi,
Could it be possible to make public the script used to produce the results for the 10x PBMC dataset? Or at least provide the matrix of barcode/Metacells.

Thanks

**Comment by sitarapersad** [comment]
Hi! Here are the labels of SEACells assignments from the submission!
[pbmc_atac_labels.csv](https://github.com/dpeerlab/SEACells/files/11160679/pbmc_atac_labels.csv)
[pbmc_rna_labels.csv](https://github.com/dpeerlab/SEACells/files/11160681/pbmc_rna_labels.csv)
