### ISSUE TITLE
PWM.h5ad in SEACells/notebooks/SEACell_tf_activity.ipynb

### ISSUE THREAD

**Issue by roshan9128** [dpeerlab/SEACells#42]
How was the pwm.h5ad file in the SEAcell_tf_activity.ipynb file constructed:

![image](https://github.com/dpeerlab/SEACells/assets/12750096/c2a71432-ea16-40db-8b9f-c29edc5d4a88)

**Comment by christinedien** [comment]
Hello,

Thank you for using SEACells! The PWM in the TF activity inference notebook was constructed using [FIMO](https://meme-suite.org/meme/doc/fimo.html) from The Meme Suite. FIMO was run with default parameters using the cisBP human v2 motif set, which can be downloaded [here](https://meme-suite.org/meme/db/motifs). 

Sequences for the "sequence file" parameter were retrieved with [SeqGL](https://github.com/ManuSetty/SeqGL)'s `get_seqs()` function using hg38 and peaks from the ATAC-seq data. `get_seqs()` takes a `.bed` file containing the peaks from the ATAC-seq data. There are other tools that can be used to retrieve sequences from the peaks for motif identification, this is just the tool we used (:

The `fimo.tsv` output file is then parsed and saved as an AnnData object with peaks as observations and identified motifs as variables.

_We acknowledge that this "PWM" is not in the traditional format of a PWM. We will be changing the name soon to reflect this and improve clarity._

Hope this helps!

**Comment by roshan9128** [comment]
Thanks for the response! Closing this ticket.
