### ISSUE TITLE
PWM for mouse genome

### ISSUE THREAD

**Issue by torkencz** [dpeerlab/SEACells#47]
Hi, 
First of all, amazing tool! I just wanted to enquire if you are thinking of making a pwm available for the mouse genome. I can figure out how to make one on my own, but was wondering if there is one available.

**Comment by ManuSetty** [comment]
Thank you for your query. We do not have one ready for mouse but you should be able to generate one using our `snakemake` pipeline here: https://github.com/settylab/atac_metacell_utilities
