### ISSUE TITLE
The data cannot be downloaded

### ISSUE THREAD

**Issue by hai178912522** [dpeerlab/SEACells#50]
This data cannot be downloaded https://dp-lab-data-public.s3.amazonaws.com/SEACells/covid_pbmcs.h5ad, please help to check.

**Comment by ManuSetty** [comment]
Sorry for the typo  in the URL. The correct link is : https://dp-lab-data-public.s3.amazonaws.com/SEACells-multiome/covid_pbmcs.h5ad
