### ISSUE TITLE
Circular import and GPU version

### ISSUE THREAD

**Issue by GLking123** [dpeerlab/SEACells#62]
Hi,

Thank you for developing such an interesting and practical tool.

1.  I encountered a 'Circular import' error while running in the cluster, the details of the error are as follows:

scanpy==1.10.1 anndata==0.10.7 umap==0.5.5 numpy==1.26.4 scipy==1.11.4 pandas==2.2.2 scikit-learn==1.4.2 statsmodels==0.14.1 igraph==0.11.4 pynndescent==0.5.12
Traceback (most recent call last):
  File "/work/home/gonglei/SEACells_test/seacell/../SEACells.py", line 4, in <module>
    import SEACells
  File "/work/home/gonglei/SEACells_test/SEACells.py", line 65, in <module>
    model = SEACells.core.SEACells(ad,
AttributeError: partially initialized module 'SEACells' has no attribute 'core' (most likely due to a circular import)

2.  Another important point, looking forward to the release of the GPU version.

model = SEACells.core.SEACells(ad, 
                  build_kernel_on=build_kernel_on, 
                  n_SEACells=n_SEACells, 
                  n_waypoint_eigs=n_waypoint_eigs,
                  convergence_epsilon = 1e-5)

it prints out (" Welcome to SEACells!")  How to call the GPU version？

Thanks!

**Comment by christophechu** [comment]
re-install SEACells from github can give you the chance to using GPU by adding use_gpu=True
