### ISSUE TITLE
model.fit taking too long?

### ISSUE THREAD

**Issue by rargelaguet** [dpeerlab/SEACells#7]
Hello,
I've been going through the [computation notebook](https://github.com/dpeerlab/SEACells/blob/main/notebooks/SEACell_computation.ipynb) of SEAcells 0.2.0, but I get stuck at this step:

```
model = SEACells.core.SEACells(ad, 
                  build_kernel_on=build_kernel_on, 
                  n_SEACells=n_SEACells, 
                  n_waypoint_eigs=n_waypoint_eigs,
                  waypt_proportion=waypoint_proportion,
                  convergence_epsilon = 1e-5)

model.fit(n_iter=1)
```

The tutorial states that it should take ~5min, but it has been running for hours in a 8-core machine. I tried downsampling cells to 1.5k and still has been running for an hour. Any idea what is going on? 

Here is the output:

```
Building kernel...
Computing kNN graph using scanpy NN ...
OMP: Info #273: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Computing radius for adaptive bandwidth kernel...
100%
1720/1720 [00:00<00:00, 3748.03it/s]
Making graph symmetric...
Computing RBF kernel...
100%
1720/1720 [00:00<00:00, 1737.40it/s]
Building similarity LIL matrix...
100%
1720/1720 [00:00<00:00, 2886.20it/s]
Constructing CSR matrix...
Building kernel on X_pca
Computing diffusion components from X_pca for waypoint initialization ... 
Determing nearest neighbor graph...
```

Thanks,
Ricard

**Comment by ManuSetty** [comment]
This function is just calling the `scanpy` neighborhood computation at the point where is stuck: https://github.com/dpeerlab/Palantir/blob/3679b9e84c9f75c147ea13b3434f387a21893c30/src/palantir/utils.py#L55. 

Can you please verify that the a direct call to `sc.pp.neighbors` is going through without issues? This will help us debug. Thanks!

**Comment by rargelaguet** [comment]
Hi Manu,
it was indeed an issue with my environment. For a reason that I have not figured ou, numba was getting stuck when using multithreading in a python>=3.10 environment. I've created a new environment with python 3.9 and now this works. I'll close the issue.
